version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/

volumes:
  mongodb_data_container:


